name: Integration CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 * * * *" # Every hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: GA - Initialize the proccess
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "17"
        cache: 'npm'
    - run: npm i
    - run: npm run dev

  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: GA - Initialize the proccess
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "17"
        cache: 'npm'
    - run: npm i
    - run: npm run test

  cron-job:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: |-
        timestamp=$(date -u)
        echo Hello FADILXCODER @ ${timestamp} || exit 0
